# Generated by Django 4.1.7 on 2023-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='picture',
            field=models.FileField(default='Somestring', upload_to='media/'),
        ),
    ]
