# Generated by Django 4.1.7 on 2023-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_note_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='mygroup',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
