# Generated by Django 4.1.7 on 2023-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_mygroup_permissions_mygroup_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='mygroup',
            name='permissions',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
