# Generated by Django 4.1.7 on 2023-05-02 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_mygroup_permissions_mygroup_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
