# Generated by Django 3.2.18 on 2023-05-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_note_groups'),
        ('authentication', '0005_alter_note_picture'),
    ]

    operations = [
    ]
