# Generated by Django 3.2.18 on 2023-05-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_note_picture'),
        ('authentication', '0005_mygroup_owner'),
    ]

    operations = [
    ]
